#
# Traefik Forward Auth Deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-forward-auth
  labels:
    app: traefik-forward-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-forward-auth
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: traefik-forward-auth
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        env:
        - name: DEFAULT_PROVIDER
            value: "oidc"
        - name: PROVIDERS_OIDC_ISSUER_URL
            valueFrom:
            secretKeyRef:
                name: sso-secret
                key: issuerurl
        - name: PROVIDERS_OIDC_CLIENT_ID
            valueFrom:
            secretKeyRef:
                name: sso-secret
                key: clientid
        - name: PROVIDERS_OIDC_CLIENT_SECRET
            valueFrom:
            secretKeyRef:
                name: sso-secret
                key: clientsecret
        - name: SECRET
            valueFrom:
            secretKeyRef:
                name: sso-secret
                key: jwtsecret
        - name: LOG_LEVEL
            value: trace

