apiVersion: v1
kind: Service
metadata:
  name: traefikauth
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4181
  selector:
    app: traefik-forward-auth