apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
spec:
  forwardAuth:
    address: http://{{ printf "%s.%s" .Values.appName .Release.Namespace }}.svc:4181
    authResponseHeaders:
      - X-Forwarded-User
    trustForwardHeader: true

    # http://vault.tooling.svc:8200