apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
spec:
  forwardAuth:
    address: 'https://{{ .Values.host }}{{ .Values.authPath }}'
    # TODO remove
    tls:
      insecureSkipVerify: true