apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
spec:
  forwardAuth:
    address: 'https://{{ .Values.authHost }}{{ .Values.authPath }}'
    authResponseHeaders:
      - X-Forwarded-User
    # TODO remove
    tls:
      insecureSkipVerify: true