apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
spec:
  forwardAuth:
    address: 'http://traefik-forward-auth-service.networking.svc:4181'
    authResponseHeaders:
      - X-Forwarded-User
      - X-Forwarded-Groups
    # TODO remove
    tls:
      insecureSkipVerify: true