apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.middleware.name }}
spec:
  forwardAuth:
    address: http://{{ printf "%s.%s" .Values.appName .Release.Namespace }}:4181{{ .Values.authPath }}
    authResponseHeaders:
      - X-Forwarded-User
    trustForwardHeader: true